version: '3.9'

services:
  postgres:
    image: postgres:latest
    ports:
      - "54320:5432"
    volumes:
      - data:/data/postgres
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - PGDATA= /data/postgres
    restart: unless-stopped
    container_name: postgres

volumes:
  data: