spring:
  datasource:
    url: jdbc:postgresql://localhost:54320/customer
    username: admin
    password: admin

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
